import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { AiFillPlayCircle } from 'react-icons/ai'
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <nav className={styles.nav}>
          <div className={styles.logo}>
            <img src="/dv20.png" alt="Logo" />
          </div>

          <ul className={styles.navLink}>
            <li>
              <Link href="/">Episode</Link>
            </li>
            <li>
              <Link href="/">Episode</Link>
            </li>
            <li>
              <Link href="/">Episode</Link>
            </li>
            <li>
              <Link href="/">Episode</Link>
            </li>
          </ul>
        </nav>
        <header className={styles.header}>
          <div className={styles.text}>
            <h1>
              Where Passion <br /> Meets Inspiration.
            </h1>
            <div className={styles.spanText}>
              <span>
                Bringing to you inspiring, educating, motivating and
                transforming interviews from pro drummers and other music
                professionals.
              </span>
            </div>
          </div>
          <div className={styles.text2}>
            <p>Drums</p>
          </div>
        </header>
        <section className={styles.pPod}>
          <img src="/dv22.png" alt="" />
          <p>Play Latest Podcast</p>
        </section>
        <section className={styles.section}>
          <span>Beats</span>
          <p>Music</p>
          <div className={styles.podcast}>
            <img src="/dv06.png" alt="" />
            <img src="/dv05.png" alt="" />
            <img src="/dv04.png" alt="" />
            <img src="/dv03.png" alt="" />
            <img src="/dv02.png" alt="" />
            <img src="/dv01.png" alt="" />
          </div>
        </section>
        <section className={styles.images}>
          <div className={styles.img1}></div>
          <div className={styles.img2}></div>
          <div className={styles.img3}></div>
          <div className={styles.img4}></div>
        </section>

        <section className={styles.podCastSec}>
          <h1>Podcasts</h1>
          <div className={styles.castSecOption}>
            <div className={styles.castCont}>
              <img src="/dv14.png" alt="" />
              <div className={styles.castText}>
                <h3>Bringing back the tradition</h3>
                <p>
                  It is a long established fact that a reader will be distracted
                  by the readable content of a page when looking at its layout.
                </p>
                <button>
                  <AiFillPlayCircle />
                  Play
                </button>
              </div>
            </div>
            <div className={styles.castCont}>
              <img src="/dv15.png" alt="" />
              <div className={styles.castText}>
                <h3>Bringing back the tradition</h3>
                <p>
                  It is a long established fact that a reader will be distracted
                  by the readable content of a page when looking at its layout.
                </p>
                <button>
                  <AiFillPlayCircle />
                  Play
                </button>
              </div>
            </div>
            <div className={styles.castCont}>
              <img src="/dv13.png" alt="" />
              <div className={styles.castText}>
                <h3>Bringing back the tradition</h3>
                <p>
                  It is a long established fact that a reader will be distracted
                  by the readable content of a page when looking at its layout.
                </p>
                <button>
                  <AiFillPlayCircle />
                  Play
                </button>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
