import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { AiFillPlayCircle, AiFillInstagram } from "react-icons/ai";
import { BsFacebook, BsTwitter, BsYoutube } from "react-icons/bs";
import { MdEmail } from 'react-icons/md'
import { GoKebabVertical } from 'react-icons/go'
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <nav className={styles.nav}>
          <Link href="/" className={styles.logo}>
            <img src="/dv20.png" alt="Logo" />
          </Link>
          <div className={styles.ham}>
            <GoKebabVertical className={styles.hamIcon} />
            <GoKebabVertical className={styles.hamIcon} />
            <GoKebabVertical className={styles.hamIcon} />
          </div>
          <ul className={styles.navLink}>
            <li>
              <Link href="/">Episode</Link>
            </li>
            <li>
              <Link href="/">Episode</Link>
            </li>
            <li>
              <Link href="/">Episode</Link>
            </li>
            <li>
              <Link href="/">Episode</Link>
            </li>
          </ul>
        </nav>
        <header className={styles.header}>
          <div className={styles.text}>
            <h1>
              Where Passion <br /> Meets Inspiration.
            </h1>
            <div className={styles.spanText}>
              <span>
                Bringing to you inspiring, educating, motivating and
                transforming interviews from pro drummers and other music
                professionals.
              </span>
            </div>
          </div>
          <div className={styles.text2}>
            <p>Drums</p>
          </div>
        </header>
        <section className={styles.pPod}>
          <img src="/dv22.png" alt="" />
          <p>Play Latest Podcast</p>
        </section>
        <section className={styles.section}>
          <span>Beats</span>
          <p>Music</p>
          <div className={styles.podcast}>
            <img src="/dv06.png" alt="" />
            <img src="/dv05.png" alt="" />
            <img src="/dv04.png" alt="" />
            <img src="/dv03.png" alt="" />
            <img src="/dv02.png" alt="" />
            <img src="/dv01.png" alt="" />
          </div>
        </section>
        <section className={styles.images}>
          <div className={styles.img1}></div>
          <div className={styles.img2}></div>
          <div className={styles.img3}></div>
          <div className={styles.img4}></div>
        </section>

        <section className={styles.podCastSec}>
          <h1>Podcasts</h1>
          <div className={styles.castSecOption}>
            <div className={styles.castCont}>
              <img src="/dv14.png" alt="" />
              <div className={styles.castText}>
                <h3>Bringing back the tradition</h3>
                <p>
                  It is a long established fact that a reader will be distracted
                  by the readable content of a page when looking at its layout.
                </p>
                <button>
                  <AiFillPlayCircle />
                  Play
                </button>
              </div>
            </div>
            <div className={styles.castCont}>
              <img src="/dv15.png" alt="" />
              <div className={styles.castText}>
                <h3>Bringing back the tradition</h3>
                <p>
                  It is a long established fact that a reader will be distracted
                  by the readable content of a page when looking at its layout.
                </p>
                <button>
                  <AiFillPlayCircle />
                  Play
                </button>
              </div>
            </div>
            <div className={styles.castCont}>
              <img src="/dv13.png" alt="" />
              <div className={styles.castText}>
                <h3>Bringing back the tradition</h3>
                <p>
                  It is a long established fact that a reader will be distracted
                  by the readable content of a page when looking at its layout.
                </p>
                <button>
                  <AiFillPlayCircle />
                  Play
                </button>
              </div>
            </div>
          </div>

          <div className={styles.musicImage}>
            <button className={styles.view}>View All</button>

            <div className={styles.musicCap}>
              <img src="dv1.png" alt="" />
            </div>
          </div>
        </section>

        <section className={styles.blogs}>
          <h1>Blogs</h1>
          <div className={styles.blogOpt}>
            <div className={styles.BlogOptCon}>
              <img src="dv10.png" alt="" />
              <div className={styles.blogText}>
                <h3>Bringing back the tradition</h3>
                <p>
                  Lorem ipsum dolor sit amet consectetur. In risus massa
                  placerat rutrum. Odio nunc nullam a et cursus scelerisque
                  faucibus. Varius ullamcorper rhoncus.
                </p>
                <button>Read</button>
              </div>
            </div>
            <div className={styles.BlogOptCon}>
              <img src="dv12.png" alt="" />
              <div className={styles.blogText}>
                <h3>Bringing back the tradition</h3>
                <p>
                  Lorem ipsum dolor sit amet consectetur. In risus massa
                  placerat rutrum. Odio nunc nullam a et cursus scelerisque
                  faucibus. Varius ullamcorper rhoncus.
                </p>
                <button>Read</button>
              </div>
            </div>
            <div className={styles.BlogOptCon}>
              <img src="dv14.png" alt="" />
              <div className={styles.blogText}>
                <h3>Bringing back the tradition</h3>
                <p>
                  Lorem ipsum dolor sit amet consectetur. In risus massa
                  placerat rutrum. Odio nunc nullam a et cursus scelerisque
                  faucibus. Varius ullamcorper rhoncus.
                </p>
                <button>Read</button>
              </div>
            </div>
            <div className={styles.BlogOptCon}>
              <img src="dv13.png" alt="" />
              <div className={styles.blogText}>
                <h3>Bringing back the tradition</h3>
                <p>
                  Lorem ipsum dolor sit amet consectetur. In risus massa
                  placerat rutrum. Odio nunc nullam a et cursus scelerisque
                  faucibus. Varius ullamcorper rhoncus.
                </p>
                <button>Read</button>
              </div>
            </div>
            <div className={styles.BlogOptCon}>
              <img src="dv12.png" alt="" />
              <div className={styles.blogText}>
                <h3>Bringing back the tradition</h3>
                <p>
                  Lorem ipsum dolor sit amet consectetur. In risus massa
                  placerat rutrum. Odio nunc nullam a et cursus scelerisque
                  faucibus. Varius ullamcorper rhoncus.
                </p>
                <button>Read</button>
              </div>
            </div>
            <div className={styles.BlogOptCon}>
              <img src="dv11.png" alt="" />
              <div className={styles.blogText}>
                <h3>Bringing back the tradition</h3>
                <p>
                  Lorem ipsum dolor sit amet consectetur. In risus massa
                  placerat rutrum. Odio nunc nullam a et cursus scelerisque
                  faucibus. Varius ullamcorper rhoncus.
                </p>
                <button>Read</button>
              </div>
            </div>
          </div>
        </section>
        <section className={styles.comment}>
          <h1>Word on the Street</h1>
          <div className={styles.commentOpt}>
            <div className={styles.commentCon}>
              <p>
                Lorem ipsum dolor sit amet consectetur. Quam orci aliquet id non
                sed placerat. A vitae aliquam mauris feugiat suscipit. At neque
                praesent id non nisl etiam tempor pharetra dapibus.
              </p>

              <div className={styles.prof}>
                <img src="dv5.png" alt="" />
                <span>Esther Howard</span>
              </div>
            </div>
            <div className={styles.commentCon}>
              <p>
                Lorem ipsum dolor sit amet consectetur. Quam orci aliquet id non
                sed placerat. A vitae aliquam mauris feugiat suscipit. At neque
                praesent id non nisl etiam tempor pharetra dapibus.
              </p>

              <div className={styles.prof}>
                <img src="dv5.png" alt="" />
                <span>Esther Howard</span>
              </div>
            </div>
            <div className={styles.commentCon}>
              <p>
                Lorem ipsum dolor sit amet consectetur. Quam orci aliquet id non
                sed placerat. A vitae aliquam mauris feugiat suscipit. At neque
                praesent id non nisl etiam tempor pharetra dapibus.
              </p>

              <div className={styles.prof}>
                <img src="dv5.png" alt="" />
                <span>Esther Howard</span>
              </div>
            </div>
            <div className={styles.commentCon}>
              <p>
                Lorem ipsum dolor sit amet consectetur. Quam orci aliquet id non
                sed placerat. A vitae aliquam mauris feugiat suscipit. At neque
                praesent id non nisl etiam tempor pharetra dapibus.
              </p>

              <div className={styles.prof}>
                <img src="dv5.png" alt="" />
                <span>Esther Howard</span>
              </div>
            </div>
            <div className={styles.commentCon}>
              <p>
                Lorem ipsum dolor sit amet consectetur. Quam orci aliquet id non
                sed placerat. A vitae aliquam mauris feugiat suscipit. At neque
                praesent id non nisl etiam tempor pharetra dapibus.
              </p>

              <div className={styles.prof}>
                <img src="dv5.png" alt="" />
                <span>Esther Howard</span>
              </div>
            </div>
          </div>
        </section>

        <section className={styles.community}>
          <h1>Community</h1>

          <div className={styles.communityCap}>
            <img src="/dv022.png" alt="" />
            <h2>Join our community</h2>
            <p>A community of individuals united by rhythm and beat.</p>
            <button>Join</button>
          </div>
        </section>

        <footer className={styles.footer}>
          <div className={styles.footTop}>
            <Link href="/" className={styles.footLogo}>
              <img src="/dv20.png" alt="Logo" />
            </Link>
            <div className={styles.social}>
              <BsFacebook />
              <AiFillInstagram />
              <BsTwitter />
              <BsYoutube />
              <MdEmail />
            </div>
          </div>

          <div className={styles.footBottom}>
            <p>2022, Drummersville Podcast. All rights reserved.</p>
          </div>
        </footer>
      </main>
    </>
  );
}
